### ISSUE TITLE
fix detector channel plotting in pysiaf

### ISSUE THREAD

**Issue by Johannes-Sahlmann** [spacetelescope/pysiaf#1]
Ensure that pysiaf's detector channel plotting is in agreement with independent reference figures.

**Comment by shanosborne** [comment]
@Johannes-Sahlmann I'm looking over the plot_detector_channels method and found a problem with NIRSpec. It's trying to plots channels for the apertures in _getFullApertures() which are NRS_FULL_MSA1, NRS_FULL_MSA2, NRS_FULL_MSA3, NRS_FULL_MSA4. But these apertures don't have any values for XDetSize in the SIAF, which is needed for the method to run. Will these apertures eventually have these values filled in in the SIAF, or if not, what values should we be using?

**Comment by Johannes-Sahlmann** [comment]
We should be using NRS1_FULL and NRS2_FULL to plot the detector channels and probably overplot RS_FULL_MSA1, NRS_FULL_MSA2, NRS_FULL_MSA3, NRS_FULL_MSA4 for visual guidance. (see e.g. Fig. 5 of JWST-STScI-005921).

**Comment by shanosborne** [comment]
Okay, so just to confirm, _getFullApertures() should still be pulling NRS_FULL_MSA1, NRS_FULL_MSA2, NRS_FULL_MSA3, and NRS_FULL_MSA4, but when plot_detector_channels() is called, we should be pulling NRS1_FULL and NRS2_FULL instead.

**Comment by Johannes-Sahlmann** [comment]
Yes, I think so.
We may reconsider some details when we see the focal plane figure. (https://jira.stsci.edu/browse/JWSTSIAF-133)

**Comment by shanosborne** [comment]
I've attached a summary of my results in this PDF:
[pysiaf_detector_channels.pdf](https://github.com/spacetelescope/pysiaf/files/2590857/pysiaf_detector_channels.pdf)

A quick summary is that almost all of the detector channels for the apertures look good. I only found 2 issues.

1. The NIRSpec MSA apertures don't show any detector channels, which considering the fact that the NIRCam and MIRI coronagraphy apertures show their corresponding channels, makes me think that the NIRSpec MSA apertures should also include theirs. (I am no expert on NIRSpec, but that's what I gather to be logical from the information I've been looking at).
2. The FGS2 aperture appears to have an incorrect location for the raw frame origin. It should be in the lower right corner of the detector, rather than where pysiaf currently has it located, in the lower left. (This has been confirmed by 3 different focal plane layouts).

**Comment by Johannes-Sahlmann** [comment]
Thanks for this summary @shanosborne !

concerning 1. I think the NIRCam and MIRI coronagraphy plots show the channels of the underlying detector. We should do the same for NIRSpec.

concerning 2. Looks like I made a mistake in raw_to_sci and sci_to_raw then. Do you have the code to create the figures in a branch? I would then try to fix this for FGS2.

**Comment by shanosborne** [comment]
I have code to create the figures in a jupyter notebook, so I can re-run it if any changes are made or pass it along to you, but I haven't commited it in a branch. 

And sorry just to confirm, did you mean you wanted me to fix the raw/sci transformation or you wanted to fix it?
