### ISSUE TITLE
Verify AperType before plotting

### ISSUE THREAD

**Issue by shanosborne** [spacetelescope/pysiaf#48]
I tried to run `plot_all_apertures(showchannels=False, showorigin=True)` and I got `TypeError: ufunc 'isnan' not supported for the input types, and the inputs could not be safely coerced to any supported types according to the casting rule ''safe''` when it got to NIRSpec's CLEAR_GWA_OTE aperture. I believe this is because the V3IdlYAngle variable is NoneType for this aperture which caused an error on line 779 in aperture.py (although I don't know why the value is None).

**Comment by Johannes-Sahlmann** [comment]
This is because *_GWA_OTE apertures are not 'regular' apertures but they are of type TRANSFORM and encode transformation parameters. See JWST-STScI-005921 for details. 
Can you please convert this issue into something named `verify AperType before plotting` ?
Please feel free to fix it in aperture.py and then open a PR. The readme details the contribution guide.

**Comment by shanosborne** [comment]
I don't appear to have permission to ask for a reviewer on this PR - just a heads up about that (since its in the contribution guide in the readme to do this)

**Comment by Johannes-Sahlmann** [comment]
@shanosborne I gave you write permissions to the repo. Are you able to request reviewers now?

**Comment by shanosborne** [comment]
Yes I am - I just requested you to be a reviewer. Thanks!
